name: Deployment to Render.com

on:
    workflow_run:
      workflows:
        - Publish Docker Image to GHCR
      types:
        - completed


jobs:
  deploy-app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - run: curl ${{secrets.RENDER_DEPLOY_HOOK}}
